export const ADD_TO_HISTORY = 'ADD_TO_HISTORY';
export const LOAD_ANIME_LIST = 'LOAD_ANIME_LIST';
export const REMOVE_ALL_HISTORY = 'REMOVE_ALL_HISTORY';
export const REMOVE_FROM_HISTORY = 'REMOVE_FROM_HISTORY';
