// Episodes
export const LOAD_ANIME_LIST = 'LOAD_ANIME_LIST';
export const MARK_EPISODE_COMPLETE = 'MARK_EPISODE_COMPLETE';
export const UNDO_MARK_EPISODE_COMPLETE = 'UNDO_MARK_EPISODE_COMPLETE';

// Favorites
export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
export const REMOVE_ALL_FAVORITES = 'REMOVE_ALL_FAVORITES';
export const REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES';
