// Episode
export const LOAD_ANIME_LIST = 'LOAD_ANIME_LIST';
export const MARK_EPISODE_COMPLETE = 'MARK_EPISODE_COMPLETE';
export const UNDO_MARK_EPISODE_COMPLETE = 'UNDO_MARK_EPISODE_COMPLETE';

// History
export const ADD_TO_HISTORY = 'ADD_TO_HISTORY';
export const REMOVE_ALL_HISTORY = 'REMOVE_ALL_HISTORY';
export const REMOVE_FROM_HISTORY = 'REMOVE_FROM_HISTORY';

// Favorite
export const ADD_TO_FAVORITE = 'ADD_TO_FAVORITE';
export const REMOVE_ALL_FAVORITE = 'REMOVE_ALL_FAVORITE';
export const REMOVE_FROM_FAVORITE = 'REMOVE_FROM_FAVORITE';
